### ISSUE TITLE
Optional fields are always set to zeroed values

### ISSUE THREAD

**Issue by omarkilani** [near/borsh-go#13]
Hi there,

It looks like borsh-go always sets optional fields to a zero value:

https://github.com/near/borsh-go/blob/master/borsh.go#L223

So a round-trip encode/decode where the fields aren't set in the encoded value ends up with set fields with zero values in the decoded value.

Is this intentional?

**Comment by ouromoros** [comment]
It's a bug that needs to be fixed since it breaks the one-to-one mapping between object instance and serialized data. Will you be interested to fix it? @omarkilani

**Comment by omarkilani** [comment]
Hey @ouromoros,

I have a fix for this in my local checkout but it's more involved than it seems.

I just wonder if the original devs had some reason for doing it the way it is right now...

**Comment by ouromoros** [comment]
@omarkilani As I originially wrote it, I'm sorry to say that it's just a point that I have missed and also failed to cover in the basic/fuzz test cases.

At first glance it doesn't seem to be much code change, but we do need to bump up a new version for it. You're welcom to submit your fix.

**Comment by holykol** [comment]
Hello @omarkilani, @ouromoros. I've submitted PR with fix. The fix is pretty simple actually. Care to merge?

**Comment by omarkilani** [comment]
@holykol nice!

I made this same change locally, but I forget why I didn't submit it.

Something to do with the fuzzer maybe?

Anyway, if it passes the test suite then 👍
