### ISSUE TITLE
how to Deserialize option field

### ISSUE THREAD

**Issue by binnz** [near/borsh-go#9]
```
pub struct Order {
    account_type: Header,
    mint: Pubkey,
    user: Pubkey,
    token_mint: Option<Pubkey>,
    price: u64,
}

type Pubkey [32]byte
```
like this rust struct, how to Deserialize use borsh in golang?

**Comment by frol** [comment]
@ouromoros Can you help here, please?

**Comment by ouromoros** [comment]
`Option<Pubkey>` would correspond to `*Pubkey` type in Go here. The doc should have made it clear.
